# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
# Website: https://github.com/jeffreytse/jekyll-theme-yat
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 初心者のためのPythonデータ分析ガイド
email: stem.sci.tech.eng.math.2013@gmail.com
author: stemtazoo
copyright: "© 2024-{currentYear} <a href='https://github.com/stemtazoo'>{author}</a> | 初心者のためのPythonデータ分析ガイド"
description: >- # this means to ignore newlines until "baseurl:"
  仕事や趣味で得たPythonデータ分析の知見を初心者向けに共有。
  基本から応用まで、誰でも実践できる情報を提供します！
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: stemtazoo
github_username:  stemtazoo

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.markdown
#  - archives.html
#  - categories.html
#  - tags.html
  - about.html

# Page default value
defaults:
  home:
    heading: "初心者のためのPythonデータ分析ガイド"
    subheading: |
      仕事や趣味で得たPythonデータ分析の知見を初心者向けに共有。
      基本から応用まで、誰でも実践できる情報を提供します！
    #banner: "Your image url"

# Build settings
# theme: minima
theme: jekyll-theme-yat

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
